backtest:
  benchmark: null
  cache_dir: ./cache
  commission_rate: 0.0003
  concurrent_loading: true
  enable_cache: true
  frequency: 1d
  initial_cash: 1000000.0
  max_workers: 4
  memory_optimization: true
  min_commission: 5.0
  slippage: 0.001
data_sources:
  akshare:
    cache_dir: ./cache/akshare
    cache_enabled: true
    enabled: true
    extra_params: {}
    retry_count: 3
    timeout: 30
  csv:
    cache_dir: ./cache/csv
    cache_enabled: true
    data_path: ./data/sample_data.csv
    date_column: '%Y-%m-%d'
    enabled: true
    encoding: utf-8
    extra_params: {}
    retry_count: 3
    timeout: 30
  tushare:
    cache_dir: ./cache/tushare
    cache_enabled: true
    enabled: false
    extra_params: {}
    pro_api: true
    retry_count: 3
    timeout: 30
    token: null
default_data_source: csv
logging:
  backup_count: 5
  file_handler: true
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
  log_dir: ./logs
  max_file_size: 10485760
reports:
  formats:
  - txt
  - json
  - csv
  include_charts: false
  output_dir: ./reports
