services:
  simtradelab-web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: simtradelab-web
    ports:
      - "8000:8000"
    volumes:
      # 持久化数据目录
      - ../data:/app/data
      - ../strategies:/app/strategies
      - ../reports:/app/reports
      - ../cache:/app/cache
      - ../web/uploads:/app/web/uploads
      # 配置文件
      - ../simtradelab_config.yaml:/app/simtradelab_config.yaml:ro
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - SIMTRADELAB_LOG_LEVEL=INFO
      - SIMTRADELAB_CACHE_DIR=/app/cache
      - SIMTRADELAB_REPORTS_DIR=/app/reports
      - SIMTRADELAB_NO_BROWSER=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  default:
    name: simtradelab-network